#!/usr/bin/env bash
#Install Nginx on server (web-01)

sudo apt update
sudo apt install -y nginx
ufw allow 'Nginx HTTP'
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www
echo 'Hello World' > /var/www/html/index.html
