#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
let file="/var/run/myscript.pid"
terminate()
{
	rm file
	exit
}

while :
do
	echo "$!" > file
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminate echo "I hate the kill command"' SIGTERM SIGQUIT
done
