#!/usr/bin/env bash
#print text after certain iteration
i=1
while [ $i -lt 21 ]
do
        case $i in
                5)
                        echo "bad luck from china"
                        ;;
                10)
                        echo "back luck from Japan"
                        ;;
                18)
                        echo "back luck from Italy"
                        ;;
        esac
        echo "$i"
        ((i++))
done

