#!/usr/bin/env bash
#check for file validity
file="$1"
if test -f "$file";then
	echo "school file exists"
	test -f "$file"; gut=$?
	if [ $gut = 0 ];then
		echo "school is not empty"
	else
		echo "school is empty"
	fi
	test -f "$file"; stat=$?
	if [ $stat = 0 ];then
		echo "school file is a regular file"
	else
		echo
	fi
else
	echo "school file does not exist"
fi

